# Generated by Django 4.0.1 on 2022-02-14 16:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('max_speed', models.TextField(max_length=200)),
                ('year', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/')),
            ],
            managers=[
                ('cars', django.db.models.manager.Manager()),
            ],
        ),
    ]
