# Generated by Django 4.0.1 on 2022-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='year',
            field=models.IntegerField(),
        ),
    ]
